name: Lab-3

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 20

    env:
      WORKING_DIR: ./lab-3

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
        working-directory: ${{ env.WORKING_DIR }}

      - run: npm test
        working-directory: ${{ env.WORKING_DIR }}
